### ISSUE TITLE
Page cannot be instantiated

### ISSUE THREAD

**Issue by BogdanJelerRO** [FluentLenium/FluentLenium#446] opened 2016-12-16 15:53 UTC
I am using TestNG + Fluentlenium TestNG 3.0.4 . I have a BaseTestNG as a baseclass from which I derive all my TestSuites. 

When I try to instantiate a page using the annotation @Page , I get this error 

I need to mention some very important aspects like : 
1. The Driver lifecycle is set on JVM. I have problem with just one page, after I already executed one test which has also one Page instantiated. 
2. The error occures in the beforeMethod of the second test 
3. I have no dedicated behaviour for the beforeMethod in my BaseTestNG class 

org.fluentlenium.core.inject.FluentInjectException: com.elektrobit.sota.dashboard.SOTAPage can't be instantiated.
	at org.fluentlenium.core.inject.DefaultContainerInstanciator.newInstance(DefaultContainerInstanciator.java:32)
	at org.fluentlenium.core.inject.FluentInjector.initChildrenContainers(FluentInjector.java:189)
	at org.fluentlenium.core.inject.FluentInjector.inject(FluentInjector.java:114)
	at org.fluentlenium.core.inject.FluentInjector.inject(FluentInjector.java:106)
	at org.fluentlenium.core.FluentDriver.inject(FluentDriver.java:64)
	at org.fluentlenium.core.inject.ContainerFluentControl.inject(ContainerFluentControl.java:17)
	at org.fluentlenium.adapter.FluentAdapter.initFluent(FluentAdapter.java:109)
	at org.fluentlenium.adapter.FluentTestRunnerAdapter.starting(FluentTestRunnerAdapter.java:95)
	at org.fluentlenium.adapter.testng.FluentTestNg.beforeMethod(FluentTestNg.java:70)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:100)
	at org.testng.internal.Invoker.invokeConfigurationMethod(Invoker.java:515)
	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:216)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:590)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:811)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1137)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)

**Comment by Toilal** [comment] 2016-12-16 19:11
Please paste the cause too ... At line 32 of DefaultContainerInstantiator, we are handling catch of InvocationTargetException so this type of exception should appear is the cause. 

There's probably an exception thrown in the constructor of SOTAPage.

**Comment by filipcynarski** [comment] 2016-12-16 21:05
@BogdanJelerRO could you please share your code here, so we can advise what can be wrong w/ you tests.

**Comment by BogdanJelerRO** [comment] 2016-12-19 09:17
Hi , sorry , I made a mistake that I saw very late . The ticket is not relevant anymore, but I will take the opportunity to ask you another thing . 

I want to declare FluentWebElements using @FindBy. I tried multiple ways of declaring the elements like : 

@FindBy(how=How.xpath , using = "..") or 
@FindBy (xpath = "...") 
private FluentWebElement createCampaign;

I always get an error that the lazy element was not identified by id or name , somehow it ignores the find by . Thanks you very much for your support and great job

**Comment by filipcynarski** [comment] 2016-12-19 09:20
@BogdanJelerRO are you using 2 findbys for one variable?

**Comment by BogdanJelerRO** [comment] 2016-12-19 09:21
no, it was just an example of how I tried to use the FindBy  (that's why I wrote the or )

**Comment by filipcynarski** [comment] 2016-12-19 09:22
good, @BogdanJelerRO please paste your stacktrace so I can advise.

**Comment by BogdanJelerRO** [comment] 2016-12-19 09:26
Ok, I recreated a short scenarios . For this element I get this error. But this happens also if I want to declare elements by xpath or class name 

  @FindBy(linkText = "Campaign Configurator")
    public FluentWebElement campaignConfigurator;


org.openqa.selenium.NoSuchElementException: Element by id or name "campaignConfigurator" (first) (Lazy Element) is not present
For documentation on this error, please visit: http://seleniumhq.org/exceptions/no_such_element.html
Build info: version: '3.0.1', revision: '1969d75', time: '2016-10-18 09:49:13 -0700'
System info: host: 'ER01504P', ip: '10.8.52.148', os.name: 'Windows 7', os.arch: 'amd64', os.version: '6.1', java.version: '1.8.0_60'
Driver info: driver.version: unknown

	at org.fluentlenium.core.domain.ElementUtils.noSuchElementException(ElementUtils.java:25)

	at org.fluentlenium.core.proxy.AbstractLocatorHandler.noSuchElement(AbstractLocatorHandler.java:167)

	at org.fluentlenium.core.proxy.ComponentHandler.getLocatorResultImpl(ComponentHandler.java:73)

	at org.fluentlenium.core.proxy.ComponentHandler.getLocatorResultImpl(ComponentHandler.java:17)

	at org.fluentlenium.core.proxy.AbstractLocatorHandler.getLocatorResult(AbstractLocatorHandler.java:140)

	at org.fluentlenium.core.proxy.AbstractLocatorHandler.invoke(AbstractLocatorHandler.java:270)

	at org.fluentlenium.core.proxy.ComponentHandler.invoke(ComponentHandler.java:98)

	at com.sun.proxy.$Proxy17.click(Unknown Source)

	at org.fluentlenium.core.domain.FluentWebElement.click(FluentWebElement.java:114)

	at com.elektrobit.sota.dashboard.SOTAPageTestSuites.createSotaCampaign(SOTAPageTestSuites.java:19)

	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)

	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)

	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)

	at java.lang.reflect.Method.invoke(Method.java:497)

	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:100)

	at org.testng.internal.Invoker.invokeMethod(Invoker.java:646)

	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:811)

	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1137)

	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)

	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)

	at org.testng.TestRunner.privateRun(TestRunner.java:753)

	at org.testng.TestRunner.run(TestRunner.java:607)

	at org.testng.SuiteRunner.runTest(SuiteRunner.java:368)

	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:363)

	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:321)

	at org.testng.SuiteRunner.run(SuiteRunner.java:270)

	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)

	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)

	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1284)

	at org.testng.TestNG.runSuitesLocally(TestNG.java:1209)

	at org.testng.TestNG.runSuites(TestNG.java:1124)

	at org.testng.TestNG.run(TestNG.java:1096)

	at org.gradle.api.internal.tasks.testing.testng.TestNGTestClassProcessor.runTests(TestNGTestClassProcessor.java:136)

	at org.gradle.api.internal.tasks.testing.testng.TestNGTestClassProcessor.stop(TestNGTestClassProcessor.java:80)

	at org.gradle.api.internal.tasks.testing.SuiteTestClassProcessor.stop(SuiteTestClassProcessor.java:59)

	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)

	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)

	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)

	at java.lang.reflect.Method.invoke(Method.java:497)

	at org.gradle.messaging.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:35)

	at org.gradle.messaging.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:24)

	at org.gradle.messaging.dispatch.ContextClassLoaderDispatch.dispatch(ContextClassLoaderDispatch.java:32)

	at org.gradle.messaging.dispatch.ProxyDispatchAdapter$DispatchingInvocationHandler.invoke(ProxyDispatchAdapter.java:93)

	at com.sun.proxy.$Proxy2.stop(Unknown Source)

	at org.gradle.api.internal.tasks.testing.worker.TestWorker.stop(TestWorker.java:116)

	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)

	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)

	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)

	at java.lang.reflect.Method.invoke(Method.java:497)

	at org.gradle.messaging.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:35)

	at org.gradle.messaging.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:24)

	at org.gradle.messaging.remote.internal.hub.MessageHub$Handler.run(MessageHub.java:360)

	at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:54)

	at org.gradle.internal.concurrent.StoppableExecutorImpl$1.run(StoppableExecutorImpl.java:40)

	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)

	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)

	at java.lang.Thread.run(Thread.java:745)

**Comment by filipcynarski** [comment] 2016-12-19 10:12
@BogdanJelerRO maybe you should wait for your element to be present before click.

Please try w/ adding await before.

```
await().atMost(30, TimeUnit.SECONDS).until(campaignConfigurator).present();
campaignConfigurator.click();
```

From your stacktrace I see the element wasn't present on page.

**Comment by BogdanJelerRO** [comment] 2016-12-19 11:17
I have tried, it does not work,  the thing is it always search for the element by id or class name, but it does not work when I want to find it by xpath or linkText

**Comment by filipcynarski** [comment] 2016-12-19 11:24
@BogdanJelerRO it is working for you when you are using CSS selectors but not when you are using xpath or linkText? I'm not sure that I got it correctly?

**Comment by BogdanJelerRO** [comment] 2016-12-19 12:46
In my case, if I declare a FluentWebElement, it ignores completely the findby (no matter the locator) , it always try to search by the id or name . Or if I want to find it by linktext for eg, I need to use dirrectly the fluentlenium syntax :  $(By.linkText("Campaign Configurator")).click();

**Comment by filipcynarski** [comment] 2016-12-19 12:59
@BogdanJelerRO which version of FluentLenium are you using? I'll try to reproduce your issue or if you can add an archive with example

**Comment by BogdanJelerRO** [comment] 2016-12-19 13:02
@filipcynarski 

  testCompile ("org.fluentlenium:fluentlenium-assertj:3.0.4")
    testCompile ("org.fluentlenium:fluentlenium-testng:3.0.4")
    testCompile ("org.seleniumhq.selenium:selenium-java:3.0.1")
    testCompile ("org.seleniumhq.selenium:selenium-htmlunit-driver:2.52.0")
    testCompile ("org.eclipse.jetty.websocket:websocket-server:9.4.0.M1")
    testCompile ("org.eclipse.jetty.websocket:websocket-client:9.4.0.M1")
    testCompile ("org.eclipse.jetty.websocket:websocket-api:9.4.0.M1")
    testCompile ("net.serenity-bdd:serenity-core:1.1.42")         
    testCompile ("net.serenity-bdd:serenity-junit:1.1.42")

I also have another weird behaviour .  I have this method in a Page Object class . 
When  I call this method  like :  sotaPage.clickOnTab("Campaign Configurator");  I have the same problem . It cannot find the element. If I debug it , everything seems to work fine

public void clickOnTab(String giveTabName)
    {
        await().atMost(20, TimeUnit.SECONDS).until($(By.linkText(giveTabName))).clickable();
        
        $(By.linkText(giveTabName)).click();
    }

**Comment by filipcynarski** [comment] 2016-12-19 13:38
@BogdanJelerRO could you please prepare an example archive with classes and structure of your project to let me investigate what may be wrong on our on your end?

**Comment by BogdanJelerRO** [comment] 2016-12-19 14:14
[src - Copy.zip](https://github.com/FluentLenium/FluentLenium/files/661250/src.-.Copy.zip)

**Comment by filipcynarski** [comment] 2016-12-20 10:02
@BogdanJelerRO thanks for the example of your project. I have to spend more time on it because you haven't set gradle, maven or something which makes it up and running on demand.

You said that on debug mode it works for you? Am I right? If yes you need to implement await everywhere where it is required.

I can take a look on that but I'd like to share my thoughts w/ you.

Could you please take a look on your code:

```
 $(By.linkText(giveTabName)).click();
```

This one means that it is going to click on object which may be a list.

please replace $ with el and check is it fixing your issue

```
 el(By.linkText(giveTabName)).click()
```

And let me know is it still causing issues on your end.

**Comment by BogdanJelerRO** [comment] 2016-12-20 10:59
Hi Filip, thanks alot for your suggestion . 

I upgraded fluentlenium to 3.1.0 and downgraded the selenium version to 2.53.1 and the FindBy is now working. I think there are still some conflicts with selenium 3. 

Thanks alot for your suggestions and for helping me, I will continue with this versions cause I see it is working

**Comment by filipcynarski** [comment] 2016-12-20 11:13
@BogdanJelerRO I think you should use Selenium 3, we are not using Selenium 2 in FluentLenium. I'm also using Selenium 3.0.1 with FluentLenium 3.0.5 in my company where we're maintaining > 500 test suite. So it should work. I may suggest dependencies check in your project. You can start using maven if you are not using it yet to detect such conflicts and issues by dependency tree feature for example.

**Comment by BogdanJelerRO** [comment] 2016-12-20 12:17
Cannot use Maven , cause Gradle is used by our project, but somehow I don't know why the FindBy are not working with selenium 3

**Comment by filipcynarski** [comment] 2016-12-20 12:20
Gradle should have such features too :)

**Comment by filipcynarski** [comment] 2016-12-20 12:39
@BogdanJelerRO I'm closing the issue please feel free to open new one if you need further assistance

**Closed by filipcynarski** 2016-12-20 12:39 UTC
