### ISSUE TITLE
await() doesn't find a new element in a list of FluentWebElement's

### ISSUE THREAD

**Issue by spikeyfish2** [FluentLenium/FluentLenium#489] opened 2017-03-20 21:36 UTC
We're having issues getting FluentLenium to pick up a new element in an array of elements populated by the FindBy annotation. The new element, in this case, is populated as a result of an async call to a REST API. 

I've produced an example project to illustrate the issue, which has two tests in - both are behaviourally identical, however one uses await() and the other Thread.sleep(). The one using Thread.sleep() works, however the await() one fails, which is what we're seeing in our main project. 

In the example, we're using the following FindBy annotation: 

```
@FindBy(css = ".alert")
List<FluentWebElement> alerts;
```

Where one alert already exists on page load: 

```
<div class="alert alert-success">
This is an alert that exists on page load
</div>
```

We then have a Javascript method, associated with a button click, that performs an AJAX GET request to a slow (~3 seconds) service. Once this completes, it adds another alert to the DOM under the first alert. It's this second alert that never gets found when using: 

```
await().atMost(10, TimeUnit.SECONDS).until(alerts).size(2);
```

However this succeeds using the following: 

```
Thread.sleep(6000);
assertThat(alerts.size()).isEqualTo(2);
```

I've uploaded a [repository on Github](https://github.com/spikeyfish2/FluentLenium-Issue) to illustrate the issue, and I'm hosting the sample website on [http://fluent.blundell.io/](http://fluent.blundell.io/).

Any help with this would be appreciated - thanks!

**Comment by Toilal** [comment] 2017-03-20 21:45
Thanks for details, i'll try to reproduce and investigate.

**Comment by Toilal** [comment] 2017-03-20 21:51
I think there's a design issue in FluentLenium element list proxy causing the list of found element to never be refreshed during the wait until invocation.

**Comment by Toilal** [comment] 2017-03-22 22:48
I confirm the issue, reproduced in a new unit test.

**Comment by spikeyfish2** [comment] 2017-03-23 08:12
Thanks for confirming @Toilal :)

**Comment by filipcynarski** [comment] 2017-03-23 12:26
In a meantime you can workaround the issue writing

```java
await().untilPredicate((fl) ->$(".alert").size() == 2);
```

**Comment by filipcynarski** [comment] 2017-03-23 12:27
@Toilal I've reported this issue before but haven't worked on that yet. I'll close related issues and leave this one as far as you started working on this here.

**Comment by filipcynarski** [comment] 2017-04-18 09:58
Here are my findings:
- awaits are working on list of elements, so list cannot be retrieved again because we are passing some elements and there is no option to read the list on every single cycle of wait loop
- I'm not sure it is bad, now it works in this way some people may rely on that
- users should use predicates to wait for AJAX elements
- we can change await to not accept fluent lazy locators or change fluent lazy locators behavior in both cases I think we have to change implementation of await method in terms of accepted arguments list
- we can deprecate current way of await definition and propose new method of waiting
- Honestly predicates are good enough for me, do we really need another method of waiting?

**Comment by Toilal** [comment] 2017-04-18 11:25
Users can use predicates as a workaround, but imho it's an issue. Also, using a predicate gives error messages that are less meaningful.

await() could reset the proxy chain before checking the condition, to effectively search the underlying element on each cycle of wait loop. This change is not that easy to implement, I did some investigations some days ago and was a bit stuck, but it should be possible.

Let's keep this one open. I'll try to fix it when I have more spare time.

**Comment by filipcynarski** [comment] 2017-04-18 12:51
@Toilal ok, good, I think reset is not working as I'm expecting if you put breakpoint after JS execution (which is changing a list size) and try to invoke reset on proxy you won't see changed number but the number of starting size when page was displayed. Maybe the reset method is a key.

**Comment by witi83** [comment] 2017-07-05 12:14
Hey, any news on this? We've also encountered this problem recently.

**Comment by filipcynarski** [comment] 2017-07-05 12:36
@witi83 no progress yet, there is too much work for me in the company for which I'm working for. But I'm keeping it in mind and will work on that soon :) If anybody is eager to help please free to fork the related branch and fix it if not I can expect it will be fixed soon (I hope in next month).

**Comment by filipcynarski** [comment] 2017-09-28 21:59
Issue resolved, preparing to release

**Closed by filipcynarski** 2017-09-28 21:59 UTC
Labels: bug
