### ISSUE TITLE
Code get stuck after calling mouse().moveToElement()

### ISSUE THREAD

**Issue by Kingyo** [FluentLenium/FluentLenium#925] opened 2019-08-12 14:22 UTC
Hello,

Since Google Chrome updated itself to 76.0.3809.100, I had to update my chromedriver to 76.0.3809.68 and I also updated selenium to 3.141.59.
I am running with the latest Fluentlenium version 4.3.0.

Before the update, I used mouse().moveToElement() without any problems.
Now, when I call it the code doesn't crash, it just gets stuck and doesn't respond.
I tried to replace the Fluent's moveToElement with Selenium's actions.moveToElement and it worked. But I don't want to replace my fluent code with selenium's one.

If anyone has an idea on how to solve this issue.

**Comment by picimako** [comment] 2019-08-12 19:29
Hi @Kingyo!
Thank you for contacting us.

I ran into this issue too recently so I can tell that it can be reproduced elsewhere too. It might be a good starting point that it works with Selenium.
We will investigate and try to fix the issue.

**Comment by Kingyo** [comment] 2019-08-13 08:25
Hi,

Yes indeed, it seems like all methods calling the Actions class are having this issue.
Thank you for your answer, I guess I have to wait a bit!

**Comment by slawekradzyminski** [comment] 2019-08-13 09:01
Thanks @Kingyo. I was trying to update docker-selenium in our project and had to revert for unknown reason (whole test suite got stuck and I didn't have time to investigate). Now I know why. Probably we would have to release hotfix version.

**Comment by puresk** [comment] 2019-08-14 06:45
Same err, Actions class with new Chromedriver doesn't work. There is a need to update selenium for this reason and after that, i am stuck.

**Comment by slawekradzyminski** [comment] 2019-08-15 06:37
Until we fix it workaround has to be used

```java
new Actions(getDriver())                .moveToElement(getDriver().findElement(By.cssSelector("#search_button_homepage")))
                .click()
                .perform();
```

**Comment by slawekradzyminski** [comment] 2019-08-15 06:48
So there are 4 cases. Only one works

1. FluentWebElement + @FindBy injection - not working
2. FluentWebElement + normal search - not working
3. WebElement + @FindBy injection - not working
4. WebElement + normal search - working

```java
// Not working 1
        searchButton.mouse().moveToElement().click();

        // Not working 2
        el(By.cssSelector("#search_button_homepage")).mouse().moveToElement().click();

        // Not working 3
        new Actions(getDriver())
                .moveToElement(searchButtonWebElement)
                .click()
                .perform();

        // working
        new Actions(getDriver())
                .moveToElement(getDriver().findElement(By.cssSelector("#search_button_homepage")))
                .click()
                .perform();
```

**Comment by slawekradzyminski** [comment] 2019-08-24 18:24
Code is hanging on while loop which has no fallback exit mechanism

```java
public Object asArg() {
      Object arg = originObject;
      while (arg instanceof WrapsElement) {
        arg = ((WrapsElement) arg).getWrappedElement();
      }
      return arg;
    }
```

Stacktrace from thread dump

```
at org.openqa.selenium.interactions.PointerInput$Origin.asArg(PointerInput.java:204)
	at org.openqa.selenium.interactions.PointerInput$Move.encode(PointerInput.java:155)
	at org.openqa.selenium.interactions.Sequence.encode(Sequence.java:75)
	at org.openqa.selenium.interactions.Sequence.toJson(Sequence.java:84)
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(java.base@11.0.3/Native Method)
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(java.base@11.0.3/NativeMethodAccessorImpl.java:62)
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(java.base@11.0.3/DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(java.base@11.0.3/Method.java:566)
	at org.openqa.selenium.json.JsonOutput.convertUsingMethod(JsonOutput.java:328)
	at org.openqa.selenium.json.JsonOutput.lambda$new$16(JsonOutput.java:155)
	at org.openqa.selenium.json.JsonOutput$$Lambda$180/0x000000080026c040.consume(Unknown Source)
	at org.openqa.selenium.json.JsonOutput.write(JsonOutput.java:264)
	at org.openqa.selenium.json.JsonOutput.lambda$null$21(JsonOutput.java:168)
	at org.openqa.selenium.json.JsonOutput$$Lambda$199/0x0000000800271040.accept(Unknown Source)
	at java.util.LinkedHashMap$LinkedValues.forEach(java.base@11.0.3/LinkedHashMap.java:608)
	at org.openqa.selenium.json.JsonOutput.lambda$new$22(JsonOutput.java:168)
	at org.openqa.selenium.json.JsonOutput$$Lambda$186/0x000000080026d840.consume(Unknown Source)
	at org.openqa.selenium.json.JsonOutput.write(JsonOutput.java:264)
	at org.openqa.selenium.json.JsonOutput.lambda$null$23(JsonOutput.java:177)
	at org.openqa.selenium.json.JsonOutput$$Lambda$196/0x0000000800270440.accept(Unknown Source)
	at com.google.common.collect.SingletonImmutableBiMap.forEach(SingletonImmutableBiMap.java:65)
	at org.openqa.selenium.json.JsonOutput.lambda$new$24(JsonOutput.java:176)
	at org.openqa.selenium.json.JsonOutput$$Lambda$188/0x000000080026e040.consume(Unknown Source)
	at org.openqa.selenium.json.JsonOutput.write(JsonOutput.java:264)
	at org.openqa.selenium.json.JsonOutput.write(JsonOutput.java:255)
	at org.openqa.selenium.json.Json.toJson(Json.java:42)
	at org.openqa.selenium.remote.http.AbstractHttpCommandCodec.encode(AbstractHttpCommandCodec.java:227)
	at org.openqa.selenium.remote.http.AbstractHttpCommandCodec.encode(AbstractHttpCommandCodec.java:117)
	at org.openqa.selenium.remote.HttpCommandExecutor.execute(HttpCommandExecutor.java:152)
	at org.openqa.selenium.remote.service.DriverCommandExecutor.execute(DriverCommandExecutor.java:83)
	at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:552)
	at org.openqa.selenium.remote.RemoteWebDriver.perform(RemoteWebDriver.java:618)
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(java.base@11.0.3/Native Method)
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(java.base@11.0.3/NativeMethodAccessorImpl.java:62)
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(java.base@11.0.3/DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(java.base@11.0.3/Method.java:566)
	at org.openqa.selenium.support.events.EventFiringWebDriver.lambda$new$1(EventFiringWebDriver.java:105)
	at org.openqa.selenium.support.events.EventFiringWebDriver$$Lambda$317/0x00000008002d7040.invoke(Unknown Source)
	at com.sun.proxy.$Proxy17.perform(Unknown Source)
	at org.openqa.selenium.support.events.EventFiringWebDriver.perform(EventFiringWebDriver.java:360)
	at org.openqa.selenium.interactions.Actions$BuiltAction.perform(Actions.java:639)
	at org.openqa.selenium.interactions.Actions.perform(Actions.java:595)
	at org.fluentlenium.core.action.MouseElementActions.moveToElement(MouseElementActions.java:129)
	at org.fluentlenium.examples.pages.DuckDuckMainPage.testActions(DuckDuckMainPage.java:47)
	at org.fluentlenium.examples.test.actions.MouseActionsTest.move(MouseActionsTest.java:15)
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(java.base@11.0.3/Native Method)
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(java.base@11.0.3/NativeMethodAccessorImpl.java:62)
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(java.base@11.0.3/DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(java.base@11.0.3/Method.java:566)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.fluentlenium.adapter.junit.FluentTestRule$1.evaluate(FluentTestRule.java:45)
	at org.junit.rules.RunRules.evaluate(RunRules.java:20)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.fluentlenium.adapter.junit.FluentTest$2.evaluate(FluentTest.java:53)
	at org.junit.rules.RunRules.evaluate(RunRules.java:20)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:68)
	at com.intellij.rt.execution.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:47)
	at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:242)
	at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:70)

```

**Comment by slawekradzyminski** [comment] 2019-08-24 19:48
Chromedriver since 75 has Actions implementation which is W3C compliant.

Chromedriver 74 was using fallback implementation from this piece of code. 75+ goes with _try_. It's Selenium `Actions` class.

```java
@Override
    public void perform() {
      if (driver == null) {
        // One of the deprecated constructors was used. Fall back to the old way for now.
        fallBack.perform();
        return;
      }

      try {
        ((Interactive) driver).perform(sequences.values());
      } catch (ClassCastException | UnsupportedCommandException e) {
        // Fall back to the old way of doing things. Old Skool #ftw
        fallBack.perform();
      }
    }
```

**Comment by slawekradzyminski** [comment] 2019-08-26 10:55
It's done, will be released soon

**Closed by slawekradzyminski** 2019-08-26 10:55 UTC
Labels: bug

**Comment by Kingyo** [comment] 2019-08-26 10:58
Thanks a lot for your work! :)

**Comment by puresk** [comment] 2019-08-27 05:45
Which version release?

**Comment by slawekradzyminski** [comment] 2019-08-28 08:12
It's released now. 4.3.1 (Java 11) and 3.9.1 (Java 8)

**Comment by slawekradzyminski** [comment] 2019-08-28 12:18
@Kingyo @puresk can you confirm that the issue is resolved?

**Comment by Kingyo** [comment] 2019-08-28 12:19
@slawekradzyminski I am currenctly working on it. I will keep you in touch as soon as I am done.

**Comment by puresk** [comment] 2019-08-28 13:37
@slawekradzyminski Yeah, i will try to redo changes i made and see.
