### ISSUE TITLE
"Caused by" error message discarded

### ISSUE THREAD

**Issue by RachelKoldenhoven** [FluentLenium/FluentLenium#583] opened 2018-03-27 17:17 UTC
https://github.com/FluentLenium/FluentLenium/blob/40a2bf3f9ccf7eded66049c4c724241f094ca5ac/fluentlenium-core/src/main/java/org/fluentlenium/adapter/FluentTestRunnerAdapter.java#L115

Due to the line above, detailed messages do not appear in logs:
```
com.example.demo.ProductUAT > testHomePage FAILED
    org.openqa.selenium.WebDriverException
```

This makes debugging FluentLenium issues difficult. This is because the line above uses this constructor:
```
  public WebDriverException(String message) {
    super(message);
  }
```

Were it to use this constructor:

```
  public WebDriverException(String message, Throwable cause) {
    super(message, cause);
  }
```

Then users would see details about the true cause, making debugging CI much easier.

Thanks!

**Comment by filipcynarski** [comment] 2018-03-28 07:25
@RachelKoldenhoven please take a look at the code again, I think we are calling the proper method 

```
try {
            sharedWebDriver = getSharedWebDriver(parameters);
        } catch (ExecutionException | InterruptedException e) {
            this.failed(testClass, testName);

            String causeMessage = this.getCauseMessage(e);

            throw new WebDriverException("Browser failed to start, test [ " + testName + " ] execution interrupted."
                    + (isEmpty(causeMessage) ? "" : "\nCaused by: [ " + causeMessage + "]"), e);
        }
```

Where `e` is passed as a cause

**Comment by filipcynarski** [comment] 2018-03-28 07:26
I think the reason is different, but I can agree it is annoying and we have to fix it finally.

**Comment by RachelKoldenhoven** [comment] 2018-03-29 19:52
Sorry about that, the issue must have been gradle log levels hiding the stack trace. Thanks for responding!

**Comment by filipcynarski** [comment] 2018-04-01 18:15
Let's reopen the issue. I think we should fix this issue whatever the cause is :)

**Comment by slawekradzyminski** [comment] 2019-01-06 20:00
Closing - Gradle settings was the root cause

**Closed by slawekradzyminski** 2019-01-06 20:01 UTC
Labels: feature
