### ISSUE TITLE
Annotation Processors not working in java 10/11

### ISSUE THREAD

**Issue by paulsjohnson91** [FluentLenium/FluentLenium#631] opened 2018-10-11 11:13 UTC
In java 10 and 11, lazy objects are initializing.

## Expected Behavior
```
@Page
private ExamplePage examplePage;

goTo(examplePage)
```
@Page object should initialize and FluentLenium should go to the page

## Current Behavior
examplePage is null so is throwing a NullPointerException.

This also happens with lazy locators with @FindBy

## Context (Environment)
Tried with both Java 10 and 11 on FluentLenium version 3.7.0

**Comment by koryl** [comment] 2018-10-17 12:16
Thank you for your feedback! FluentLenium was checked mainly for jdk8 and I will try to find the reason for such behavior in newer versions. It is important for us to bring FL to the upcoming Java 11.

**Comment by paulsjohnson91** [comment] 2019-01-02 15:48
Unfortunately I'm still getting the same issues as before. 

`java.lang.IllegalArgumentException: Page is mandatory`

The annotators are not initialising the page objects.

Checked on version 4.0.0. with Java 11

**Comment by slawekradzyminski** [comment] 2019-01-02 15:49
@paulsjohnson91 Can you please share complete class code?

**Comment by paulsjohnson91** [comment] 2019-01-02 16:10
`  private final String BO_USERNAME = prop("operatorUserName");
  private final String BO_PASSWORD = prop("operatorPassword");

  @Page
  private LogInPage logInPage;

  @Page
  private DashboardPage dashboardPage;

  @Before
  public void before(Scenario scenario) {
    super.setUpBefore(scenario);
  }

  @After
  public void after(Scenario scenario) {
    super.tearDownAfter(scenario);
  }

  @Given("^the operator navigates to back office login page$")
  public void the_operator_navigates_to_back_office_login_page() {
    goTo(logInPage);
    logInPage.isAt();
  }
`

**Comment by slawekradzyminski** [comment] 2019-01-02 16:16
@paulsjohnson91 please copy/paste everything with imports. That would be helpful :)

**Comment by slawekradzyminski** [comment] 2019-01-02 20:14
Can you try to extend `FluentCucumberTest` as stated in docs?
http://fluentlenium.org/docs/test-runners/#cucumber

**Comment by paulsjohnson91** [comment] 2019-01-03 18:19
Hi The AbstractCucumberTest class extends the FluentCucumberTest class.

Thanks,

**Comment by koryl** [comment] 2019-01-04 08:40
Hi @paulsjohnson91, I was trying reproduce mentioned by you issue and I found out that it is not related with Java 11 because it worked for me smoothly.

Please, make sure that your runner class uses 
`@RunWith(FluentCucumber.class)`
instead of 
`@RunWith(Cucumber.class)`
When using Cucumber.class as runner I've noticed the problem and message you have mentioned (but not always which is confusing). When using FluentCucumber.class it worked well.

Let us know if it resolves your issue.

**Comment by paulsjohnson91** [comment] 2019-01-04 10:14
Hi, For the scenario listed above I was not running with a runner I was running directly from the IDE. When we use runners we are using AbstractTestNGCucumberTests not JUnit. This setup was working before with Java8 using both the IDE and the TestNG runner to execute the tests.

**Comment by koryl** [comment] 2019-01-04 16:49
I've merged bugfix to develop and it will be incorporated into next version.
@paulsjohnson91, this fix will resolve problem with creating instances of Pages but not with elements annotates with FindBy. If this is still an issue please try earlier mentioned FluentCucumber runner or create elements with use FluentWebElement element = el("#locator") instead.

**Comment by paulsjohnson91** [comment] 2019-01-04 20:42
Great thanks, the page issue was fixed by this as long as I added the following to my test step classes:
`  @Before
  public void before(Scenario scenario){
    super.before(scenario);
  }`

I'm not currently having issues with elements which are initialised with @Findby so everything seems to be working as expected now.

Thanks for the help

**Closed** 2019-01-04 21:58 UTC
Labels: bug, cucumber
